### ISSUE TITLE
Support for mac

### ISSUE THREAD

**Issue by athityakumar** [kaustubhhiware/NotiFyre#7]
For supporting Mac,

1. Change dependency from `notify-send` to `terminal-notifier` which is easily installable with `brew install terminal-notifier`

2. Change the `notify-send` call statements like the below -

```console
terminal-notifier -title "Terminal Notifier" -subtitle "Command : $commandx" -message "Completed in $(($(date +%s) - start)) seconds" -timeout 5 -closeLabel 'Gotcha!'
```

**Comment by kaustubhhiware** [comment]
Closed in favour of #8
